services:
  mtproto:
    container_name: mtproto-proxy
    image: ghcr.io/codinv/mtproto
    restart: unless-stopped
    ports:
      - "443:8443"       # change host port (e.g. 443:8443, 2053:8443), container port MUST stay 8443
    environment:
      - SECRET=xxxx      # your own 32-character hex secret
      - WORKERS=1        # recommended: 1 for better stability